# Meta Data for SEO

## Homepage
title = "Little Bears Playgroup"
titleSeparator = ", "
titleAddition = "an english speaking play caffe in Bern"
description = "An english speaking play cafee in Bern."

## Socialmedia
facebook = "https://www.facebook.com/groups/678038115547386/"
instagram = "https://www.instagram.com/parentstots/"

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Little Bears Playgroup"

## Twitter Cards
twitterSite = "@littlebearswelcome"
twitterCreator = "@littlebearswelcome"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Little Bears Playgroup"
schemaAuthor = "Little Bears Playgroup"
schemaAuthorTwitter = "https://twitter.com/littlebearswelcome"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/littlebearsplaygroup"
schemaLocale = "en-US"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/littlebearswelcome"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/littlebearsplaygroup"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer_old = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"
footer = "Powered by a bunch of tireless volunteers at <a href=\"https://www.littlebears.ch/\">Little Bears Playgroup</a>"

# Feed
copyRight = "Copyright (c) 2022 Little Bears Playgroup"

# Alert
alert = false
alertDismissable = true
alertText = "</a>"
