# Meta Data for SEO

## Homepage
title = "Little Bears Bern"
titleSeparator = ", "
titleAddition = "an english speaking play caffe in Bern"
description = "An english speaking play cafee in Bern."

## Socialmedia
facebook = "https://www.facebook.com/groups/678038115547386/"
instagram = "https://www.instagram.com/littlebearsbern/"

## Open Graph
images = ["littlebearsbern.png"]
ogLocale = "en_US"
titleHome = "Little Bears Bern"

## Twitter Cards
twitterSite = "@littlebearsbern"
twitterCreator = "@littlebearsbern"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Little Bears Bern"
schemaAuthor = "Little Bears Bern"
schemaAuthorTwitter = "https://twitter.com/littlebearsbern"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/littlebearsbern"
schemaLocale = "en-US"
schemaLogo = "logo-littlebearsbern.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "littlebearsbern.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/littlebearsbern"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/littlebearsbern"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer_old = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"
footer = "<a href=\"https://www.littlebearsbern.ch/\">Little Bears Bern</a>"

# Feed
copyRight = "Copyright (c) 2022 Little Bears Bern"

# Alert
alert = false
alertDismissable = true
alertText = "</a>"
